### ISSUE TITLE
Any schedule porting to Polymer?

### ISSUE THREAD

**Issue by masaoliou** [SerkanSipahi/taby#1]
Taby works perfectly in stand alone applications, but the current version can not be included in Polymer's custom element. Is there any schedule of porting to Polymer?

**Comment by SerkanSipahi** [comment]
1.) I rewrite Taby currently with ES6 from scratch with same API but before i begin, i need this lib -> https://github.com/SerkanSipahi/lyadom <- @in progress
2.) I think in 2 - 3 Weeks( make the rewrite in my freetime ) we can Porting that to Polymer

**Comment by SerkanSipahi** [comment]
see here: https://github.com/SerkanSipahi/taby/issues/3
